id = 7
title = "CTF After Dark"
short = "CTF After Dark"
date = "2/24 6:00PM PT"
description = """BEep beep? Boop boop BeeP Bop?
Youâ€™ve been training ğŸ‹ï¸all quarter (Â¼) long for this. Youâ€™ve been walking from your bed  ğŸ˜´to your computer ğŸ’»for this ğŸ¥µ. Youâ€™re tired ğŸ˜£. Momâ€™s spaghetti ğŸ. But you donâ€™t care ğŸ™…ğŸ™…â€â™€ï¸ğŸ™…â€â™‚ï¸. Your megamind brain ğŸ§  is ready for anything that comes your way. You, my dear friend ğŸ¦Œ, are an absolute unit.
Beep! Boop Beep Boop! 
Come play our ğŸš© Capture the Flag (CTF)  ğŸš©competition on Forensics ğŸ•µï¸â€â™€ï¸ğŸ‘¨â€ğŸ’» and FLEX ğŸ’ª off all that youâ€™ve learned from our workshops this Winter â„ï¸. Winners ğŸ…will be rewarded ğŸ‘€. Date and time TBD. Be there or be square ğŸŸ¨. 


More Info coming!
"""
link = ""
slides = ""
