id = 5
title = "Cyber Academy: Steganography"
short = "Steganography" 
date = "Thursday 2/10 6:00PM-8:00PM PT"
description = """Weâ€™ve all heard the saying 'a picture is worth a thousand words', but did you know that a picture could actually contain a top secret message? Come to our Steganography workshop to learn how you, too, can hide your messages in plain sight within an image, audio file, or even a physical object!

zoom link: https://ucla.zoom.us/j/95081428653?pwd=am9rb2JuK25LVmFMT3NxaHJyV3J6Zz09
"""
link = ""
slides = ""
